apiVersion: v1
kind: ReplicationController
metadata:
  name: git
  labels:
    name: git
spec:
  replicas: 1
  selector:
    name: git
  template:
    metadata:
      labels:
        name: git
    spec:
      containers:
      - name: git
        image: zhaoshuaiabc/git-patch
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "000000"
          name: MYSQL_DATABASE
          value: LTC_China_CommitInfo
        volumeMounts:
        - name: gitcode-persistent-storage
          mountPath: /code
      volumes:
      - name: gitcode-persistent-storage
        nfs:
          # This path must already exist.
          # We use this IP for PODs mount volume
          server: 10.10.0.100
          path: "/root/django/code"

