apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  labels: 
    name: mysql-master
spec: 
  replicas: 1
  selector: 
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
      - name: mysql-master
        image: mysql
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: "000000"
            name: MYSQL_DATABASE
            value: LTC_China_CommitInfo
        ports:
        - containerPort: 3306
          name: mysql-master
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        nfs:
          # This path must already exist.
          # We use this IP for PODs mount volume
          server: 10.10.0.100
          path: "/root/django/db" 
